name: Build module 1

on:
  workflow_call:

jobs:
  build:
    name: Build module 1
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/module1
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm install