name: Build

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      module1: ${{ steps.filter.outputs.module1 }}
      module2: ${{ steps.filter.outputs.module2 }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          module1:
            - 'src/module1/**'
          module2:
            - 'src/module2/**'

    - name: module 1 test
      if: steps.filter.outputs.module1 == 'true'
      run: echo "Build Module 1"

    - name: module 2 test
      if: steps.filter.outputs.module2 == 'true'
      run: echo "Build Module 2"


  build-module-1:
    uses: ./.github/workflows/build-module1.yaml
    needs: paths-filter
    if: needs.paths-filter.outputs.module1 == 'true'
  
  build-module-2:
    uses: ./.github/workflows/build-module2.yaml
    needs: paths-filter
    if: needs.paths-filter.outputs.module2 == 'true'
