name: CD
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
      project:
        description: 'Project to deploy - leave empty to deploy all projects'
        type: choice
        options: 
        - module1
        - module2
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: Install Nx
        run: ./nx

      - name: Deploy affected projects
        if: ${{ inputs.project == null }}
        run: npx nx affected -t deploy --parallel=1 --environment=${{ inputs.environment }} --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Deploy project
        if: ${{ inputs.project != null }}
        run: npx nx deploy ${{ inputs.project }} --parallel=1 --environment=${{ inputs.environment }} --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
