name: CI - Resource A

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-resource-b
        with:
          paths: modules/module1/src/resources/resource-b

      - name: Publish
        if: steps.changed-resource-b.outputs.changed == 'true'
        run: ls -a
