name: CI

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
  build-resource-a:
    uses: joensindholt/iac/.github/workflows/ci-resource-a.yml@main

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-resource-b
        with:
          paths: modules/module1/src/resources/resource-b

      - name: Publish Module 1 - Resource B
        if: steps.changed-resource-b.outputs.changed == 'true'
        run: echo "Publishing Reource B"        

      # - uses: nrwl/nx-set-shas@v4

      # - name: Install Nx
      #   run: ./nx

      # - name: Init
      #   run: npx nx affected -t init --parallel=3

      # - name: Lint
      #   run: npx nx affected -t lint --parallel=3

      # - name: Build
      #   run: npx nx affected -t build --parallel=3

      # - name: Test
      #   run: npx nx affected -t test --parallel=3
