on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: Install Nx
        run: ./nx
        
      - name: Build
        run: npx nx affected -t build --parallel=3

      - name: List output files
        run: ls -al dist