name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
    
      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-resource-a
        with:
          paths: modules/module1/src/resources/resource-a
      
      - name: CI - Resource A
        if: steps.changed-resource-a.outputs.changed == 'true'
        uses: ./.github/actions/ci-resource-a


  # build-resource-b:
  #   uses: joensindholt/iac/.github/workflows/ci-resource-b.yml@main     

      # - uses: nrwl/nx-set-shas@v4

      # - name: Install Nx
      #   run: ./nx

      # - name: Init
      #   run: npx nx affected -t init --parallel=3

      # - name: Lint
      #   run: npx nx affected -t lint --parallel=3

      # - name: Build
      #   run: npx nx affected -t build --parallel=3

      # - name: Test
      #   run: npx nx affected -t test --parallel=3
