on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: List files
        run: ls -al

      - name: Install Nx
        run: ./nx
        
      - name: List files
        run: ls -al

      - name: Build
        run: npx nx run-many -t build